const memories=[
 {label:'Nuestro tiempo',type:'counter',title:'Mi amor por ti comenzó hace…',text:'Incluso antes de llamarnos novios, mi corazón ya te había elegido.'},
 {label:'Nuestra historia',type:'text',title:'Siempre tú',text:'Cuatro años de conocerte, de elegirte de muchas maneras y de confirmar que, aun con kilómetros de por medio, sigues siendo tú.<br><br><b>26 de febrero de 2025</b> — el día en que le pusimos nombre a lo nuestro.'},
 {label:'Tu sonrisa',img:'01-eddd2766-8498-4bfb-bc98-a76f5cad1d44.jpeg',title:'Tu sonrisa',text:'Una de mis vistas favoritas en cualquier parte del universo. Hay algo en tu sonrisa que hace que, por un momento, se me olvide lo lejos que estoy. Veo esta foto y me dan ganas de estar frente a ti, haciendo cualquier tontería para verte sonreír otra vez.<br><br>Mientras llega ese momento, me quedo con esto: poder mirarte, extrañarte y saber que hay alguien a quien quiero así. Ojalá hoy tengas muchísimas razones para sonreír, mi niña, y que alguna de ellas sea este regalo.'},
 {label:'Bonita',img:'03-IMG_5993.jpeg',title:'Bonita sin esfuerzo',text:'Una de esas fotos tuyas que podría mirar mil veces. Me gusta detenerme en los detalles, en tu mirada y en esa forma tan tuya de ser bonita sin tener que hacer demasiado. Seguro tú ves una foto más; yo veo a la persona que quisiera tener cerca.<br><br>Me habría gustado decirte todo esto mirándote a los ojos. Por ahora te lo dejo aquí, guardado entre estrellas, para que puedas volver a leerlo cuando quieras y acordarte de lo mucho que me encantas.'},
 {label:'Mi niña',img:'04-IMG_5992.jpeg',title:'Mi niña',text:'La forma más bonita que encontró la vida de sorprenderme. A veces pienso en cómo una persona que antes no conocías termina siendo alguien a quien quieres contarle tu día, buscar cuando te pasa algo y tener a tu lado en los momentos importantes.<br><br>Eso me pasó contigo. Por eso te digo mi niña: porque esas dos palabras ya llevan mucho cariño, muchas ganas de cuidarte y todo lo que a veces no sé explicar tan bien. Hoy quería que también pudieras verlo.'},
 {label:'Mi lugar',img:'05-IMG_9755.jpeg',title:'Mi lugar favorito',text:'No es un lugar. Eres tú. Cuando pienso en dónde me gustaría estar hoy, no pienso en una ciudad ni en un viaje; pienso en estar contigo, escucharte y compartir tu cumpleaños sin tener que mirar una pantalla.<br><br>Me ilusiona que todavía nos queden tantas cosas sencillas por vivir: salir juntos, tomarnos una foto, quedarnos hablando sin estar pendientes de la hora. Quiero que esos momentos dejen de ser planes y empiecen a ser recuerdos nuestros.'},
 {label:'Tus versiones',img:'06-c7d26748-f0b0-47a9-83d8-eeb089d3b896.jpeg',title:'Todas tus versiones',text:'Cada una tiene algo que me vuelve a enamorar. Me gusta verte de distintas maneras, en diferentes momentos, y encontrar siempre algo que me hace pensar: qué bonita es mi niña. Esta foto tenía que tener su propia estrella.<br><br>También quiero acompañarte en los días que no salen en las fotos, cuando estás cansada o las cosas no van como esperabas. Que puedas sentir mi cariño ahí también, en lo cotidiano, mientras seguimos construyendo lo nuestro.'},
 {label:'Tu felicidad',img:'08-37e5585d-216a-40ef-9f5e-aee593ec9722.jpeg',title:'Así de feliz',text:'Así quiero verte siempre. Me hace feliz imaginarte disfrutando tu día, rodeada de cariño y sintiéndote querida. Si pudiera pedir algo para este cumpleaños, pediría que este nuevo año te dé más momentos en los que te sientas así.<br><br>Que tengas tranquilidad para ir a tu ritmo, fuerzas para lo que te propongas y personas que te hagan bien. Yo, desde donde esté, quiero seguir celebrando tus alegrías contigo y recordándote que tienes a alguien que te quiere muchísimo.'},
 {label:'Simplemente tú',img:'02-RenderedImage.jpeg',title:'Simplemente tú',text:'Y eso siempre ha sido suficiente para mí. Elegí esta foto porque me encantas tú, con tus gestos y tus maneras, con esas cosas pequeñas que te hacen reconocible entre cualquier cantidad de personas.<br><br>No sé si alcanzo a decírtelo cada vez que lo pienso, pero me gusta muchísimo tenerte en mi vida. Hoy quise ponerlo aquí, en un lugar al que puedas regresar, para que no se quede solamente en un mensaje que se pierde entre otros.'},
 {label:'Mi elección',img:'09-533adfe7-3025-4278-bfc7-2bb1740268b4.jpeg',title:'Mi elección',text:'Te elegiría otra vez. Entre todas las fotos que podía guardar aquí, esta también me hizo detenerme. Me gusta tu sonrisa, y me gusta todavía más pensar en el día en que pueda verla de cerca y salir contigo en la misma foto.<br><br>Hasta entonces, sigo queriendo hacer espacio para nosotros, incluso desde lejos. Cuando dijimos «hasta Kepler», esas palabras se quedaron conmigo. Me gusta saber que tenemos algo tan nuestro, y más todavía pensar en todo lo que nos falta por compartir.'},
 {label:'Un pedacito de ti',video:'07-1356ffdb-d38d-4ece-ba57-cad357523a9b.mov',title:'Un pedacito de ti',text:'Guardado entre mis recuerdos favoritos.'},
 {label:'Para mi niña',type:'letter',title:'Para mi niña',text:'Hoy cumples un año más de vida y, aunque me hace feliz saberlo, también me pesa no poder estar ahí contigo. Me habría encantado prepararte algo, verte sonreír, abrazarte a las doce y hacer que este día fuera exactamente como lo mereces.<br><br>La distancia me quitó la oportunidad de darte un regalo con mis propias manos, pero no podía quitarme las ganas de hacerte sentir especial. Por eso hice esto para ti: para recordarte que, aunque hoy no esté a tu lado, estoy pensando en ti en cada momento.<br><br>Deseo que tus 25 te traigan tranquilidad, experiencias bonitas y muchas razones para sonreír. Que Dios te cuide y te permita cumplir todo lo que sueñas.<br><br><span class="sign">Te amo, Wil ♡</span>'},
 {label:'Kepler',type:'final',title:'Feliz cumpleaños, mi niña',text:'25 vueltas al sol y todavía nos queda un universo entero por recorrer.'}
];
const $=id=>document.getElementById(id),canvas=$('universe'),ctx=canvas.getContext('2d'),modal=$('modal'),audio=$('music');
const birthday=Date.parse('2026-09-12T00:00:00-04:00'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
let returnView=null,closing=false;
let w=innerWidth,h=innerHeight,angle=.15,tilt=.65,distance=1450,goal=1450,panX=0,panY=0,tx=0,ty=0,started=false,paused=reduce,drag=false,lx=0,ly=0,last=0,flight=null,warp=0,arrival=false,focusIndex=-1;
let seed=250926;const rnd=()=>((seed=seed*16807%2147483647)-1)/2147483646;
const points=[],heart=[],stars=[],seen=new Set();
for(let i=0;i<8500;i++){let r=Math.pow(rnd(),.7)*780,a=(i%4)*Math.PI/2+r*.0105+(rnd()-.5)*.58;points.push({x:Math.cos(a)*r,y:(rnd()-.5)*(18+55*(1-r/780)),z:Math.sin(a)*r,s:.5+rnd()*1.7,c:i%5===0?'#ffe1f1':i%3===0?'#b15fd3':'#ff84c3'})}
for(let i=0;i<2200;i++){const a=rnd()*Math.PI*2,r=Math.sqrt(rnd());heart.push({x:16*Math.sin(a)**3*r*8,y:-(13*Math.cos(a)-5*Math.cos(2*a)-2*Math.cos(3*a)-Math.cos(4*a))*r*8-270,z:(rnd()-.5)*65,s:.5+rnd()*1.6,c:'#ff8dc2'})}
for(let i=0;i<700;i++)stars.push({x:rnd(),y:rnd(),s:.3+rnd()*1.3,p:rnd()*6});
memories[11].text='Mi niña,<br><br>Hoy quería estar ahí: abrazarte a las doce, verte sonreír y pasar este día contigo. Me da tristeza no poder hacerlo, porque hay cosas que ninguna pantalla reemplaza.<br><br>Pero tampoco quería que tu cumpleaños llegara y quedarme solo con las ganas. Por eso hice este pequeño universo para ti. Escogí tus fotos, guardé un poco de nuestra historia y pensé en esa palabra que ya significa tanto para nosotros: Kepler.<br><br>Me gusta pensar en todo lo que todavía nos falta: las fotos juntos que aún no tenemos, los cumpleaños a tu lado y esos días normales en los que no tengamos que despedirnos por una llamada.<br><br>Deseo que tus 25 te traigan paz, salud y muchas razones para sentirte feliz. Que Dios te cuide y que puedas cumplir lo que tanto deseas. Quiero seguir conociéndote, acompañándote y compartiendo la vida contigo.<br><br>Hoy no puedo darte el abrazo, pero sí recordarte algo: te amo, mi niña. Hasta Kepler.<span class="signature">Wil ♡</span>';
memories[12].title='Hasta Kepler, mi niña.';
memories[12].text='¿Te acuerdas de hasta dónde dijimos que llegaba nuestro amor?<br><br>Hasta Kepler.<br>Hoy quise traerte.<br><br><b>Felices 25, mi niña.</b><br>Nos queda un universo por vivir.';
memories.push({label:'Cerquita de ti',video:'mi-nina-descansando.mp4',title:'Hasta en los momentos más sencillos',text:'Me gusta este recuerdo porque no hace falta una ocasión especial para querer estar contigo. A veces basta con verte ahí, acostadita, y sentir que la pantalla nos presta un ratito de cercanía.<br><br>Me quedo pensando en lo bonito que será compartir esos momentos sin una llamada de por medio. Que descansar cerca de ti sea parte de un día cualquiera, y que ya no tenga que imaginar cómo sería tenerte a mi lado.'});
const nodes=memories.map((m,i)=>{const a=(i>12?i-1:i)/(memories.length-1)*Math.PI*2,r=430+(i%3)*120,b=document.createElement('button');b.className='star'+(i===12?' kepler':'');b.setAttribute('aria-label','Abrir '+m.label);b.innerHTML=(m.img?'<img src="assets/'+m.img+'" alt="" draggable="false">':'<span class="symbol">'+(i===12?'✧':'✦')+'</span>')+'<span>'+m.label+'</span>';b.onclick=()=>travel(i);$('constellation').appendChild(b);return{x:i===12?0:Math.cos(a)*r,y:i===12?-330:-20-(i%3)*65,z:i===12?-550:Math.sin(a)*r,b}});
function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function project(p){let x=p.x*Math.cos(angle)-p.z*Math.sin(angle),z=p.x*Math.sin(angle)+p.z*Math.cos(angle),y=p.y*Math.cos(tilt)-z*Math.sin(tilt),depth=p.y*Math.sin(tilt)+z*Math.cos(tilt)+distance,s=Math.min(w,h)*1.15/Math.max(depth,90);return{x:w/2+(x-panX)*s,y:h*.52+(y-panY)*s,s,depth}}
function frame(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;
if(started&&!paused&&!drag&&!modal.open&&!flight)angle+=dt*.065;
const smooth=1-Math.exp(-dt*4);distance+=(goal-distance)*smooth;panX+=(tx-panX)*smooth;panY+=(ty-panY)*smooth;
ctx.fillStyle='#030108';ctx.fillRect(0,0,w,h);
for(const s of stars){const x=s.x*w,y=s.y*h;ctx.globalAlpha=.35+.4*Math.sin(now*.0006+s.p)**2;ctx.fillStyle='#e6d9ef';ctx.fillRect(x,y,s.s,s.s);if(warp>0&&!reduce){ctx.strokeStyle='#e8c5e8';ctx.globalAlpha=warp*.55;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(x-w/2)*warp*.25,y+(y-h/2)*warp*.25);ctx.stroke()}}
ctx.globalAlpha=1;ctx.globalCompositeOperation='lighter';
for(const p of points){const q=project(p);if(q.depth<100)continue;ctx.fillStyle=p.c;ctx.globalAlpha=Math.min(.85,.28+q.s*.35);const r=Math.max(.45,p.s*q.s);ctx.fillRect(q.x,q.y,r,r)}
const pulse=reduce?1:1+Math.sin(now*.0017)*.045;
for(const p of heart){const q=project({x:p.x*pulse,y:(p.y+270)*pulse-270,z:p.z});ctx.fillStyle=arrival?'#ffd5af':p.c;ctx.globalAlpha=.65;ctx.fillRect(q.x,q.y,Math.max(.5,p.s*q.s),Math.max(.5,p.s*q.s))}
ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';
if(flight&&!flight.intro&&!reduce){const progress=Math.max(0,Math.min(1,1-(flight.end-now)/2100));ctx.save();ctx.translate(w/2,h*.52);ctx.strokeStyle='#ffc4e8';for(let j=0;j<4;j++){const r=((progress+j/4)%1)*Math.max(w,h)*.7;ctx.globalAlpha=Math.sin(progress*Math.PI)*.24*(1-r/Math.max(w,h));ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(0,0,r,r*.62,progress*.4,0,Math.PI*2);ctx.stroke()}ctx.restore()}

nodes.forEach(n=>{const q=project(n),s=Math.max(.48,Math.min(1.2,q.s));n.b.style.transform='translate('+q.x+'px,'+q.y+'px) translate(-50%,-50%) scale('+s+')';n.b.style.zIndex=String(Math.round(4000-q.depth));n.b.style.opacity=modal.open||flight?'0':String(Math.min(1,.45+q.s*.6));n.b.style.visibility=q.depth<100?'hidden':'visible';n.b.style.pointerEvents=flight||modal.open?'none':'auto'});
warp=Math.max(0,warp-dt*.7);if(flight&&now>=flight.end){const f=flight;flight=null;warp=0;if(f.intro){$('caption').classList.remove('visible');goal=1450}else show(f.i)}
requestAnimationFrame(frame)}requestAnimationFrame(frame);
function updateMotion(){$('rotation').textContent=paused?'Reanudar giro':'Pausar giro';$('rotation').setAttribute('aria-pressed',String(paused))}updateMotion();
$('rotation').onclick=()=>{paused=!paused;updateMotion()};
canvas.onpointerdown=e=>{if(flight)return;drag=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{if(!drag)return;angle+=(e.clientX-lx)*.004;tilt=Math.max(.12,Math.min(1.25,tilt+(e.clientY-ly)*.003));lx=e.clientX;ly=e.clientY};
canvas.onpointerup=canvas.onpointercancel=()=>drag=false;
canvas.addEventListener('wheel',e=>{e.preventDefault();if(!flight)goal=Math.max(1000,Math.min(2300,goal+e.deltaY*.7))},{passive:false});
function reset(){tx=ty=0;goal=1450;tilt=.65;arrival=false;$('chapter').textContent='Nuestro pequeño infinito'}
$('loveCounter').onclick=()=>travel(0);$('reset').onclick=reset;$('destination').onclick=()=>travel(12);
audio.volume=.7;async function play(){try{$('audioStatus').textContent='Cargando nuestra canción…';await audio.play()}catch{$('audioStatus').textContent='Pulsa Música para reintentar el audio.'}}
audio.onplaying=()=>{$('sound').textContent='Ⅱ Pausar música';$('sound').setAttribute('aria-pressed','true');$('audioStatus').textContent=''};
audio.onpause=()=>{$('sound').textContent='♫ Música';$('sound').setAttribute('aria-pressed','false')};
audio.onerror=()=>{$('audioStatus').textContent='No se pudo cargar la canción. Revisa la conexión y pulsa Música.'};
$('sound').onclick=()=>{if(audio.paused){if(audio.error)audio.load();play()}else audio.pause()};
$('volume').oninput=e=>audio.volume=+e.target.value;
$('enter').onclick=()=>{started=true;document.body.classList.add('started');$('entrance').classList.add('gone');$('entrance').inert=true;play();distance=2600;goal=1150;warp=1;flight={intro:true,end:performance.now()+(reduce?0:4200)};$('caption').textContent='Tú, yo… y todo lo que nos queda.';$('caption').classList.add('visible')};
function travel(i){if(!started||flight||modal.open)return;returnView={angle,tilt,distance:goal};focusIndex=i;const q=project(nodes[i]);tx=(q.x-w/2)/q.s;ty=(q.y-h*.52)/q.s;goal=850;warp=1.65;arrival=i===12;$('chapter').textContent=arrival?'Llegamos a Kepler':memories[i].label;flight={i,end:performance.now()+(reduce?0:2100)}}
function show(i){const m=memories[i];let media=m.img?'<img src="assets/'+m.img+'" alt="'+m.title+'">':m.video?'<video src="assets/'+m.video+'" autoplay muted loop playsinline controls></video>':'';
if(m.type==='counter')media='<div class="timer">'+['days','hours','minutes','seconds'].map((v,j)=>'<div><b id="'+v+'">00</b><small>'+['DÍAS','HORAS','MINUTOS','SEGUNDOS'][j]+'</small></div>').join('')+'</div>';
$('memory').innerHTML=media+'<h3 class="'+(i===12?'kepler-title':'')+'">'+m.title+'</h3><p class="'+(i===11?'letter':'')+'">'+m.text+'</p>'+(i===12?'<button class="primary" id="readLetter">Tengo algo que decirte ♡</button>':'');
if(i===12)$('readLetter').onclick=()=>{modal.close();show(11)};
seen.add(i);nodes[i].b.classList.add('seen');$('progress').textContent=seen.size+' de '+memories.length+' recuerdos descubiertos';modal.classList.remove('leaving');modal.showModal();tick()}
function close(){if(closing)return;closing=true;modal.classList.add('leaving');$('memory').querySelector('video')?.pause();setTimeout(()=>{modal.close();modal.classList.remove('leaving');reset();if(returnView){angle=returnView.angle;tilt=returnView.tilt;goal=returnView.distance}warp=reduce?0:.6;closing=false;if(focusIndex>=0)nodes[focusIndex].b.focus({preventScroll:true})},reduce?0:450)}
$('close').onclick=$('return').onclick=close;modal.addEventListener('cancel',e=>{e.preventDefault();close()});
function tick(){const delta=Math.floor((Date.now()-birthday)/1000),total=Math.max(0,1035*86400+19*3600+18*60+23+delta),v=[Math.floor(total/86400),Math.floor(total/3600)%24,Math.floor(total/60)%60,total%60];['days','hours','minutes','seconds'].forEach((id,i)=>{if($(id))$(id).textContent=String(v[i]).padStart(2,'0')});$('loveTime').textContent=v[0]+' días, '+String(v[1]).padStart(2,'0')+' horas, '+String(v[2]).padStart(2,'0')+' minutos y '+String(v[3]).padStart(2,'0')+' segundos';const left=Math.max(0,-delta);$('countdown').textContent=left?'Faltan '+Math.floor(left/86400)+' días · '+String(Math.floor(left/3600)%24).padStart(2,'0')+':'+String(Math.floor(left/60)%60).padStart(2,'0')+':'+String(left%60).padStart(2,'0')+' para tus 25':'Ya es tu día. Felices 25, mi niña.'}tick();setInterval(tick,1000);
